swagger: '2.0'
info:
  version: 0.2.1
  title: Content translation service
  description: Content translation service for translating mediawiki pages between languages.
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: the Wikimedia Language team
    url: https://www.mediawiki.org/wiki/Wikimedia_Language_engineering
  license:
    name: GPL-2.0+
    url: http://opensource.org/licenses/GPL-2.0
x-default-params:
  domain: en.wikipedia.org
paths:
  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
        - Robots
      description: Gets robots.txt
      x-amples:
        - title: robots.txt check
          request: {}
          response:
            status: 200
            headers:
              user-agent: '*'
              disallow: '/'
  /:
    get:
      tags:
        - Root
      description: The root service end-point
      produces:
        - application/json
      x-amples:
        - title: root with no query params
          request: {}
          response:
            status: 404
        - title: spec from root
          request:
            query:
              spec: true
          response:
            status: 200
        - title: root with wrong query param
          request:
            query:
              fooo: true
          response:
            status: 404
  # from routes/v1.js
  /v1/page/{language}/{title}{/revision}:
    get:
      tags:
        - Page content
      description: Fetches segmented mediawiki page
      produces:
        - application/json
      parameters:
        - name: language
          in: path
          description: The language code or the domain of the wiki
          type: string
          required: true
        - name: title
          in: path
          description: The page title
          type: string
          required: true
        - name: revision
          in: path
          description: The page revision id
          type: string
          required: false
      x-amples:
        - title: Fetch enwiki Oxygen page
          request:
            params:
              language: en
              title: Oxygen
              revision: 702870951
          response:
            status: 200
            headers:
              content-type: application/json
  /v1/dictionary/{word}/{from}/{to}{/provider}:
    get:
      tags:
        - Dictionary
      description: Fetches the dictionary meaning of a word.
      produces:
        - application/json
      parameters:
        - name: word
          in: path
          description: The word to lookup
          type: string
          required: true
        - name: from
          in: path
          description: The source language code
          type: string
          required: true
        - name: to
          in: path
          description: The target language code
          type: string
          required: true
        - name: provider
          in: path
          description: The dictionary provider id
          type: string
          required: false
          enum:
           - JsonDict
           - Dictd
      x-amples:
        - title: Fetch dictionay meaning with a given provider
          request:
            params:
              word: water
              from: en
              to: es
              provider: JsonDict
          response:
            status: 200
            body:
              source: water
              translations:
                - phrase: /.+/
                  sources:
                    - fd-eng-spa
            headers:
              content-type: application/json
        - title: Fetch dictionay meaning without specifying a provider
          request:
            params:
              word: water
              from: en
              to: es
          response:
            status: 200
            body:
              source: water
              translations:
                - phrase: /.+/
                  sources:
                    - fd-eng-spa
            headers:
              content-type: application/json
  /v1/mt/{from}/{to}{/provider}:
    post:
      tags:
        - Machine translation
      description: Fetches the machine translation. Some providers require an authorization header and it is forbidden to use them outside the Content Translation tool.
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: from
          in: path
          description: The source language code
          type: string
          required: true
        - name: to
          in: path
          description: The target language code
          type: string
          required: true
        - name: provider
          in: path
          description: The machine translation provider id
          type: string
          required: false
          enum:
           - Apertium
           - Matxin
        - name: html
          in: formData
          description: The HTML or plaintext content to translate
          type: string
          required: true
          x-textarea: true
      x-amples:
        - title: Machine translate an HTML fragment using Apertium.
          request:
            params:
              from: en
              to: es
              provider: Apertium
            body:
              html: <p><a href='Oxygen'>Oxygen</a> is a chemical element with symbol O and <a href='Atomic number'>atomic number</a> 8.</p>
          response:
            status: 200
            body:
              contents: /.+/
            headers:
              content-type: application/json
  /v1/translate/{from}/{to}{/provider}:
    post:
      tags:
        - Machine translation
      description: Translate the given content from source language to target langauge. Also adapt the content for the target language wiki. Some machine translation providers require an authorization header and it is forbidden to use them outside the Content Translation tool.
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: from
          in: path
          description: The source language code
          type: string
          required: true
        - name: to
          in: path
          description: The target language code
          type: string
          required: true
        - name: provider
          in: path
          description: The machine translation provider id
          type: string
          required: false
          enum:
           - Apertium
        - name: html
          in: formData
          description: The HTML content to translate
          type: string
          required: true
          x-textarea: true
      x-amples:
        - title: Machine translate an HTML fragment using Apertium, adapt the links to target language wiki.
          request:
            params:
              from: en
              to: es
              provider: Apertium
            body:
              html: <p><a rel="mw:WikiLink" href='Oxygen'>Oxygen</a> is a chemical element with symbol O and <a rel="mw:WikiLink" href='Atomic number'>atomic number</a> 8.</p>
          response:
            status: 200
            body:
              contents: /.+/
            headers:
              content-type: application/json
  /v1/list/tool/{tool}:
    get:
      tags:
        - Tools
        - Service information
      description: Lists the tools for all language pairs
      produces:
        - application/json
      parameters:
        - name: tool
          in: path
          description: The tool name
          type: string
          required: true
          enum:
           - mt
           - dictionary
      x-amples:
        - title: Get the tools for all language pairs
          request:
            params:
              tool: mt
          response:
            status: 200
            headers:
              content-type: application/json
  /v1/list/pair/{from}/{to}:
    get:
      tags:
        - Tools
      description: Lists the tools for a given language pair
      produces:
        - application/json
      parameters:
        - name: from
          in: path
          description: The source language code
          type: string
          required: true
        - name: to
          in: path
          description: The target language code
          type: string
          required: true
      x-amples:
        - title: Get the tools between two language pairs
          request:
            params:
              from: en
              to: es
          response:
            status: 200
            headers:
              content-type: application/json
  /v1/list/languagepairs:
    get:
      tags:
        - Languages
        - Service information
      description: Lists the language pairs supported by the server
      produces:
        - application/json
      x-amples:
        - title: Get all the language pairs
          response:
            status: 200
            headers:
              content-type: application/json
  /v1/list/{tool}{/from}{/to}:
    get:
      tags:
        - Tools
        - Service information
      description: Lists all language pairs that tool supports
      produces:
        - application/json
      parameters:
        - name: tool
          in: path
          description: The tool name
          type: string
          required: true
          enum:
           - mt
           - dictionary
        - name: from
          in: path
          description: The source language code
          type: string
          required: false
        - name: to
          in: path
          description: The target language code
          type: string
          required: false
      x-amples:
        - title: Get the MT tool between two language pairs
          request:
            params:
              from: en
              to: es
              tool: mt
          response:
            status: 200
            headers:
              content-type: application/json
  # from routes/info.js
  /_info:
    get:
      tags:
        - Service information
      description: Gets information about the service
      produces:
        - application/json
      x-amples:
        - title: retrieve service info
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              name: /.+/
              description: /.+/
              version: /.+/
              home: /.+/
  /_info/name:
    get:
      tags:
        - Service information
        - Service name
      description: Gets the name of the service
      produces:
        - application/json
      x-amples:
        - title: retrieve service name
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              name: /.+/
  /_info/version:
    get:
      tags:
        - Service information
        - Service version
      description: Gets the running version of the service
      produces:
        - application/json
      x-amples:
        - title: retrieve service version
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              version: /.+/
  /_info/home:
    get:
      tags:
        - Service information
        - Service homepage
      description: Redirects to the home page
      x-amples:
        - title: redirect to the home page
          request: {}
          response:
            status: 301
